import pandas as pd

df = pd.read_excel(r'C:\Users\zerod\OneDrive\주식 체크 리스트_20220328.xlsx', sheet_name='탐구생활', header=None)
print("=== 실제 엑셀 탐구생활 시트 구조 ===")
print("Row 0 (0번째행):", df.iloc[0].tolist())
print("Row 1 (1번째행):", df.iloc[1].tolist())
print("Row 2 (2번째행):", df.iloc[2].tolist())
print("Row 3 (3번째행):", df.iloc[3].tolist())
print("Row 4 (4번째행):", df.iloc[4].tolist())
print("Row 5 (5번째행):", df.iloc[5].tolist())
print()
print("=== pandas로 읽은 것 (헤더 있음) ===")
df2 = pd.read_excel(r'C:\Users\zerod\OneDrive\주식 체크 리스트_20220328.xlsx', sheet_name='탐구생활')
print("Columns:", df2.columns.tolist())
print("Row[0]:", df2.iloc[0].tolist())
print("Row[1]:", df2.iloc[1].tolist())
print("Row[2]:", df2.iloc[2].tolist())
print("Row[3]:", df2.iloc[3].tolist())
print("Row[4]:", df2.iloc[4].tolist())
